export const questions = {
  technical: {
    AIDS: [
      { id: "t1", topic: "Python", question: "Which of the following is used to create a virtual environment in Python?", options: ["virtualenv", "venv", "pyenv", "All of the above"], answer: "All of the above" },
      { id: "t2", topic: "Machine Learning", question: "Which algorithm is used for classification problems?", options: ["Linear Regression", "K-Means", "Random Forest", "PCA"], answer: "Random Forest" },
      { id: "t3", topic: "Data Analysis", question: "Which Python library is primarily used for data manipulation?", options: ["NumPy", "Pandas", "Matplotlib", "Scikit-learn"], answer: "Pandas" },
      { id: "t4", topic: "Deep Learning", question: "What does CNN stand for in Deep Learning?", options: ["Central Neural Network", "Convolutional Neural Network", "Connected Neural Network", "Core Neural Network"], answer: "Convolutional Neural Network" },
      { id: "t5", topic: "Database", question: "Which of the following is a NoSQL database?", options: ["MySQL", "PostgreSQL", "MongoDB", "SQLite"], answer: "MongoDB" },
      { id: "t6", topic: "Python", question: "What is the output of: print(type([]))?", options: ["<class 'tuple'>", "<class 'list'>", "<class 'array'>", "<class 'dict'>"], answer: "<class 'list'>" },
      { id: "t7", topic: "Machine Learning", question: "What is overfitting in machine learning?", options: ["Model performs well on training but poorly on test data", "Model performs poorly on both training and test data", "Model performs well on test data only", "Model has too few parameters"], answer: "Model performs well on training but poorly on test data" },
      { id: "t8", topic: "Web Development", question: "Which hook is used to manage state in React?", options: ["useEffect", "useContext", "useState", "useRef"], answer: "useState" },
      { id: "t9", topic: "Data Analysis", question: "What does EDA stand for?", options: ["Extensive Data Analysis", "Exploratory Data Analysis", "External Data Access", "Enhanced Data Algorithm"], answer: "Exploratory Data Analysis" },
      { id: "t10", topic: "Database", question: "Which command is used to retrieve data from a SQL database?", options: ["GET", "FETCH", "SELECT", "RETRIEVE"], answer: "SELECT" },
      { id: "t11", topic: "Python", question: "What is a lambda function in Python?", options: ["A named function", "An anonymous function", "A class method", "A built-in function"], answer: "An anonymous function" },
      { id: "t12", topic: "Machine Learning", question: "Which technique is used to reduce dimensionality?", options: ["Random Forest", "PCA", "KNN", "SVM"], answer: "PCA" },
      { id: "t13", topic: "Deep Learning", question: "What activation function is commonly used in output layer for binary classification?", options: ["ReLU", "Tanh", "Sigmoid", "Softmax"], answer: "Sigmoid" },
      { id: "t14", topic: "Data Analysis", question: "Which method is used to handle missing values in Pandas?", options: ["dropna()", "fillna()", "isna()", "All of the above"], answer: "All of the above" },
      { id: "t15", topic: "Web Development", question: "What does REST stand for?", options: ["Remote Execution State Transfer", "Representational State Transfer", "Resource State Transfer", "None of these"], answer: "Representational State Transfer" },
      { id: "t16", topic: "Python", question: "Which data structure in Python is immutable?", options: ["List", "Dictionary", "Tuple", "Set"], answer: "Tuple" },
      { id: "t17", topic: "Machine Learning", question: "What is the purpose of cross-validation?", options: ["To train the model faster", "To evaluate model performance on unseen data", "To reduce the dataset size", "To increase accuracy"], answer: "To evaluate model performance on unseen data" },
      { id: "t18", topic: "Database", question: "What does ACID stand for in databases?", options: ["Atomicity, Consistency, Isolation, Durability", "Access, Control, Integrity, Data", "Automated, Consistent, Isolated, Durable", "None of these"], answer: "Atomicity, Consistency, Isolation, Durability" },
      { id: "t19", topic: "Deep Learning", question: "What is the vanishing gradient problem?", options: ["Gradients become too large", "Gradients become too small making training slow", "Model overfits the data", "Loss function diverges"], answer: "Gradients become too small making training slow" },
      { id: "t20", topic: "Web Development", question: "Which HTTP method is used to update a resource?", options: ["GET", "POST", "PUT", "DELETE"], answer: "PUT" },
      { id: "t21", topic: "Python", question: "What is the difference between append() and extend() in Python lists?", options: ["No difference", "append() adds single element, extend() adds multiple", "extend() adds single element, append() adds multiple", "append() is faster"], answer: "append() adds single element, extend() adds multiple" },
      { id: "t22", topic: "Machine Learning", question: "Which algorithm is best for detecting anomalies?", options: ["Linear Regression", "Isolation Forest", "KNN", "Decision Tree"], answer: "Isolation Forest" },
      { id: "t23", topic: "Data Analysis", question: "What is the purpose of normalization in data preprocessing?", options: ["To remove duplicates", "To scale features to a similar range", "To fill missing values", "To encode categorical variables"], answer: "To scale features to a similar range" },
      { id: "t24", topic: "Database", question: "What is an index in a database?", options: ["A backup of the database", "A data structure to speed up queries", "A foreign key reference", "A stored procedure"], answer: "A data structure to speed up queries" },
      { id: "t25", topic: "Deep Learning", question: "What is dropout in neural networks?", options: ["Removing neurons permanently", "Randomly deactivating neurons during training to prevent overfitting", "Reducing learning rate", "Removing layers"], answer: "Randomly deactivating neurons during training to prevent overfitting" },
      { id: "t26", topic: "Python", question: "What is a generator in Python?", options: ["A function that returns multiple values at once", "A function that yields values one at a time", "A class for generating random numbers", "A built-in Python module"], answer: "A function that yields values one at a time" },
      { id: "t27", topic: "Machine Learning", question: "What is the bias-variance tradeoff?", options: ["Balance between model complexity and generalization", "Balance between training speed and accuracy", "Balance between data size and model size", "None of these"], answer: "Balance between model complexity and generalization" },
      { id: "t28", topic: "Web Development", question: "What is the virtual DOM in React?", options: ["A server-side rendering technique", "A lightweight copy of the real DOM for performance", "A database for React apps", "A CSS framework"], answer: "A lightweight copy of the real DOM for performance" },
      { id: "t29", topic: "Data Analysis", question: "Which Pandas function is used to group data?", options: ["pivot()", "groupby()", "merge()", "concat()"], answer: "groupby()" },
      { id: "t30", topic: "Database", question: "What is the purpose of a foreign key?", options: ["To uniquely identify each row", "To establish a relationship between two tables", "To index the table", "To encrypt data"], answer: "To establish a relationship between two tables" },
      { id: "t31", topic: "Python", question: "What does the len() function do in Python?", options: ["Returns data type", "Returns length of an object", "Adds elements", "Deletes elements"], answer: "Returns length of an object" },
      { id: "t32", topic: "Machine Learning", question: "Which algorithm is commonly used for clustering?", options: ["K-Means", "Logistic Regression", "Linear Regression", "Naive Bayes"], answer: "K-Means" },
      { id: "t33", topic: "Data Analysis", question: "Which library is used for data visualization in Python?", options: ["NumPy", "Pandas", "Matplotlib", "TensorFlow"], answer: "Matplotlib" },
      { id: "t34", topic: "Deep Learning", question: "Which framework is widely used for deep learning?", options: ["Django", "Flask", "TensorFlow", "Bootstrap"], answer: "TensorFlow" },
      { id: "t35", topic: "Database", question: "Which SQL clause is used to filter records?", options: ["ORDER BY", "WHERE", "GROUP BY", "JOIN"], answer: "WHERE" },
      { id: "t36", topic: "Web Development", question: "Which language is used to style web pages?", options: ["HTML", "Python", "CSS", "SQL"], answer: "CSS" },
      { id: "t37", topic: "Python", question: "What is the purpose of the 'self' keyword in Python?", options: ["Refers to class itself", "Refers to instance of the class", "Creates new object", "Deletes object"], answer: "Refers to instance of the class" },
      { id: "t38", topic: "Machine Learning", question: "Which metric is used to evaluate classification models?", options: ["Mean Squared Error", "Accuracy", "RMSE", "R-squared"], answer: "Accuracy" },
      { id: "t39", topic: "Data Analysis", question: "What is a DataFrame in Pandas?", options: ["A single column", "A 2D labeled data structure", "A visualization tool", "A database"], answer: "A 2D labeled data structure" },
      { id: "t40", topic: "Deep Learning", question: "Which layer is responsible for feature extraction in CNN?", options: ["Dense layer", "Pooling layer", "Convolutional layer", "Output layer"], answer: "Convolutional layer" },
      { id: "t41", topic: "Database", question: "Which SQL keyword is used to remove duplicates?", options: ["UNIQUE", "DISTINCT", "REMOVE", "DELETE"], answer: "DISTINCT" },
      { id: "t42", topic: "Web Development", question: "Which JavaScript method is used to select an element by ID?", options: ["getElementById()", "querySelectorAll()", "getElementsByClassName()", "selectElement()"], answer: "getElementById()" },
      { id: "t43", topic: "Python", question: "Which keyword is used for exception handling in Python?", options: ["try", "catch", "handle", "error"], answer: "try" },
      { id: "t44", topic: "Machine Learning", question: "Which type of learning uses labeled data?", options: ["Unsupervised Learning", "Reinforcement Learning", "Supervised Learning", "Semi-supervised Learning"], answer: "Supervised Learning" },
      { id: "t45", topic: "Data Analysis", question: "Which operation combines two datasets vertically in Pandas?", options: ["merge()", "join()", "concat()", "append()"], answer: "concat()" },
      { id: "t46", topic: "Deep Learning", question: "Which optimizer is commonly used in deep learning?", options: ["SGD", "Adam", "RMSprop", "All of the above"], answer: "All of the above" },
      { id: "t47", topic: "Database", question: "Which SQL statement is used to delete a table?", options: ["REMOVE TABLE", "DELETE TABLE", "DROP TABLE", "CLEAR TABLE"], answer: "DROP TABLE" },
      { id: "t48", topic: "Web Development", question: "Which protocol is used to transfer web pages?", options: ["FTP", "HTTP", "SMTP", "TCP"], answer: "HTTP" },
      { id: "t49", topic: "Python", question: "What is the output of bool(0)?", options: ["True", "False", "None", "Error"], answer: "False" },
      { id: "t50", topic: "Machine Learning", question: "Which algorithm is used for regression tasks?", options: ["K-Means", "Decision Tree", "Linear Regression", "Apriori"], answer: "Linear Regression" }
    ],
    CSE: [
      { id: "t1", topic: "DSA", question: "What is the time complexity of Binary Search?", options: ["O(n)", "O(log n)", "O(n²)", "O(1)"], answer: "O(log n)" },
      { id: "t2", topic: "OS", question: "What is a deadlock in operating systems?", options: ["A process that runs forever", "A situation where processes wait for each other indefinitely", "A memory overflow error", "A CPU scheduling algorithm"], answer: "A situation where processes wait for each other indefinitely" },
      { id: "t3", topic: "Networks", question: "What does HTTP stand for?", options: ["HyperText Transfer Protocol", "High Transfer Text Protocol", "Hyper Transfer Text Process", "None"], answer: "HyperText Transfer Protocol" },
      { id: "t4", topic: "DSA", question: "Which data structure uses LIFO?", options: ["Queue", "Stack", "Tree", "Graph"], answer: "Stack" },
      { id: "t5", topic: "OOP", question: "Which OOP concept allows a class to inherit from multiple classes?", options: ["Polymorphism", "Encapsulation", "Multiple Inheritance", "Abstraction"], answer: "Multiple Inheritance" },
      { id: "t6", topic: "Database", question: "What is a primary key?", options: ["A key that can have duplicate values", "A unique identifier for each record", "A foreign key reference", "An index key"], answer: "A unique identifier for each record" },
      { id: "t7", topic: "OS", question: "What is virtual memory?", options: ["RAM that is physically installed", "Memory on the GPU", "A technique that uses disk space as extended RAM", "Cache memory"], answer: "A technique that uses disk space as extended RAM" },
      { id: "t8", topic: "DSA", question: "Which sorting algorithm has the best average case complexity?", options: ["Bubble Sort", "Selection Sort", "Merge Sort", "Insertion Sort"], answer: "Merge Sort" },
      { id: "t9", topic: "Networks", question: "Which layer of OSI model handles routing?", options: ["Data Link", "Transport", "Network", "Session"], answer: "Network" },
      { id: "t10", topic: "OOP", question: "What is polymorphism?", options: ["Hiding data from outside", "One interface, multiple implementations", "Inheriting from a parent class", "Creating objects"], answer: "One interface, multiple implementations" },
      { id: "t11", topic: "DSA", question: "What is the time complexity of inserting into a hash table?", options: ["O(n)", "O(log n)", "O(1) average", "O(n²)"], answer: "O(1) average" },
      { id: "t12", topic: "OS", question: "Which scheduling algorithm gives the shortest waiting time?", options: ["FCFS", "Round Robin", "SJF", "Priority"], answer: "SJF" },
      { id: "t13", topic: "Networks", question: "What is the purpose of ARP?", options: ["Assign IP addresses", "Map IP addresses to MAC addresses", "Route packets", "Encrypt data"], answer: "Map IP addresses to MAC addresses" },
      { id: "t14", topic: "DSA", question: "What is the height of a balanced BST with n nodes?", options: ["O(n)", "O(log n)", "O(n²)", "O(1)"], answer: "O(log n)" },
      { id: "t15", topic: "OOP", question: "What is encapsulation?", options: ["Inheriting properties", "Hiding internal implementation details", "Creating multiple objects", "Method overriding"], answer: "Hiding internal implementation details" },
      { id: "t16", topic: "Database", question: "What is normalization?", options: ["Backing up data", "Organizing data to reduce redundancy", "Encrypting data", "Indexing data"], answer: "Organizing data to reduce redundancy" },
      { id: "t17", topic: "OS", question: "What is a semaphore?", options: ["A type of memory", "A synchronization tool to control access to shared resources", "A CPU register", "A file system"], answer: "A synchronization tool to control access to shared resources" },
      { id: "t18", topic: "Networks", question: "What is the difference between TCP and UDP?", options: ["TCP is faster", "TCP is reliable and connection-oriented, UDP is faster but unreliable", "UDP is more secure", "No difference"], answer: "TCP is reliable and connection-oriented, UDP is faster but unreliable" },
      { id: "t19", topic: "DSA", question: "Which traversal visits root first in a binary tree?", options: ["Inorder", "Postorder", "Preorder", "Level order"], answer: "Preorder" },
      { id: "t20", topic: "OOP", question: "What is abstraction in OOP?", options: ["Showing all implementation details", "Hiding complexity and showing only essential features", "Creating multiple instances", "Overloading methods"], answer: "Hiding complexity and showing only essential features" },
      { id: "t21", topic: "DSA", question: "What is dynamic programming?", options: ["Programming with dynamic languages", "Breaking problems into subproblems and storing results", "Runtime code generation", "Object-oriented programming"], answer: "Breaking problems into subproblems and storing results" },
      { id: "t22", topic: "OS", question: "What is thrashing in OS?", options: ["High CPU utilization", "Excessive paging causing low CPU utilization", "Memory leak", "Process starvation"], answer: "Excessive paging causing low CPU utilization" },
      { id: "t23", topic: "Networks", question: "What is DNS?", options: ["Domain Name System that translates domain names to IP addresses", "Data Network Service", "Dynamic Network Security", "None"], answer: "Domain Name System that translates domain names to IP addresses" },
      { id: "t24", topic: "DSA", question: "What is the space complexity of merge sort?", options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: "O(n)" },
      { id: "t25", topic: "Database", question: "What is a JOIN in SQL?", options: ["Combining rows from two or more tables", "Deleting duplicate rows", "Creating a new table", "Updating records"], answer: "Combining rows from two or more tables" },
      { id: "t26", topic: "OS", question: "What is the difference between process and thread?", options: ["No difference", "Process is heavyweight with its own memory, thread shares memory", "Thread is slower", "Process is part of a thread"], answer: "Process is heavyweight with its own memory, thread shares memory" },
      { id: "t27", topic: "Networks", question: "What is subnetting?", options: ["Connecting two networks", "Dividing a network into smaller sub-networks", "Encrypting network traffic", "Assigning MAC addresses"], answer: "Dividing a network into smaller sub-networks" },
      { id: "t28", topic: "DSA", question: "What is a graph in data structures?", options: ["A chart", "A non-linear data structure with vertices and edges", "A type of tree", "A linear data structure"], answer: "A non-linear data structure with vertices and edges" },
      { id: "t29", topic: "OOP", question: "What is method overloading?", options: ["Same method name, different parameters", "Same method in child class", "Creating multiple classes", "Hiding methods"], answer: "Same method name, different parameters" },
      { id: "t30", topic: "Database", question: "What is a transaction in a database?", options: ["A query", "A unit of work that is either fully completed or fully rolled back", "A stored procedure", "An index"], answer: "A unit of work that is either fully completed or fully rolled back" },
      { id: "t31", topic: "DSA", question: "Which data structure is used for BFS traversal?", options: ["Stack", "Queue", "Heap", "Tree"], answer: "Queue" },
      { id: "t32", topic: "OS", question: "What is context switching?", options: ["Switching between CPUs", "Saving and loading process state", "Deleting a process", "Allocating memory"], answer: "Saving and loading process state" },
      { id: "t33", topic: "Networks", question: "Which protocol is used for secure communication over the internet?", options: ["HTTP", "FTP", "HTTPS", "SMTP"], answer: "HTTPS" },
      { id: "t34", topic: "DSA", question: "What is the worst-case time complexity of Quick Sort?", options: ["O(n log n)", "O(n²)", "O(log n)", "O(n)"], answer: "O(n²)" },
      { id: "t35", topic: "OOP", question: "Which concept binds data and methods together?", options: ["Inheritance", "Encapsulation", "Polymorphism", "Abstraction"], answer: "Encapsulation" },
      { id: "t36", topic: "Database", question: "What is a foreign key?", options: ["Unique identifier", "Key linking two tables", "Primary key", "Index"], answer: "Key linking two tables" },
      { id: "t37", topic: "OS", question: "What is paging?", options: ["Memory allocation technique", "CPU scheduling", "File system method", "Disk formatting"], answer: "Memory allocation technique" },
      { id: "t38", topic: "DSA", question: "Which data structure is used in recursion?", options: ["Queue", "Stack", "Heap", "Graph"], answer: "Stack" },
      { id: "t39", topic: "Networks", question: "Which layer ensures reliable data transfer?", options: ["Network", "Transport", "Session", "Application"], answer: "Transport" },
      { id: "t40", topic: "OOP", question: "What is method overriding?", options: ["Same method name different parameters", "Redefining method in subclass", "Deleting a method", "Creating multiple methods"], answer: "Redefining method in subclass" },
      { id: "t41", topic: "DSA", question: "What is a heap?", options: ["A linear structure", "A complete binary tree", "A graph", "A linked list"], answer: "A complete binary tree" },
      { id: "t42", topic: "OS", question: "What is a kernel?", options: ["Application software", "Core part of operating system", "Device driver", "Shell command"], answer: "Core part of operating system" },
      { id: "t43", topic: "Networks", question: "What is the default port for HTTP?", options: ["21", "25", "80", "443"], answer: "80" },
      { id: "t44", topic: "DSA", question: "Which algorithm is used to find shortest path in a graph?", options: ["DFS", "BFS", "Dijkstra", "Kruskal"], answer: "Dijkstra" },
      { id: "t45", topic: "Database", question: "What is a view in SQL?", options: ["A table copy", "A virtual table based on a query", "A database schema", "An index"], answer: "A virtual table based on a query" },
      { id: "t46", topic: "OS", question: "What is starvation?", options: ["Process gets too much CPU", "Process never gets CPU resources", "Memory overflow", "Deadlock resolution"], answer: "Process never gets CPU resources" },
      { id: "t47", topic: "Networks", question: "What is a MAC address?", options: ["IP address", "Physical address of a device", "Network protocol", "Routing table"], answer: "Physical address of a device" },
      { id: "t48", topic: "DSA", question: "Which data structure is best for implementing priority queue?", options: ["Stack", "Queue", "Heap", "Array"], answer: "Heap" },
      { id: "t49", topic: "OOP", question: "Which keyword is used to inherit a class in Java?", options: ["implements", "inherits", "extends", "super"], answer: "extends" },
      { id: "t50", topic: "Database", question: "Which SQL command is used to update existing records?", options: ["MODIFY", "CHANGE", "UPDATE", "SET"], answer: "UPDATE" }
    ],
    IT: [
      { id: "t1", topic: "Web Development", question: "Which of the following is a JavaScript framework?", options: ["Django", "Flask", "React.js", "Laravel"], answer: "React.js" },
      { id: "t2", topic: "Networks", question: "What is the full form of DNS?", options: ["Domain Name System", "Data Network Service", "Dynamic Name Server", "Digital Network System"], answer: "Domain Name System" },
      { id: "t3", topic: "Database", question: "Which of these is a cloud database service?", options: ["MongoDB Atlas", "MySQL Workbench", "SQLite", "phpMyAdmin"], answer: "MongoDB Atlas" },
      { id: "t4", topic: "Web Development", question: "What does REST stand for?", options: ["Remote Execution State Transfer", "Representational State Transfer", "Resource State Transfer", "None"], answer: "Representational State Transfer" },
      { id: "t5", topic: "Security", question: "What is SQL Injection?", options: ["A database backup method", "An attack that inserts malicious SQL code", "A query optimization technique", "A type of join"], answer: "An attack that inserts malicious SQL code" },
      { id: "t6", topic: "Web Development", question: "Which HTTP method is used to update a resource?", options: ["GET", "POST", "PUT", "DELETE"], answer: "PUT" },
      { id: "t7", topic: "Networks", question: "What is the purpose of a firewall?", options: ["Speed up internet", "Monitor and control network traffic", "Store network data", "Assign IP addresses"], answer: "Monitor and control network traffic" },
      { id: "t8", topic: "Database", question: "What is normalization in databases?", options: ["Backing up data", "Organizing data to reduce redundancy", "Encrypting data", "Indexing data"], answer: "Organizing data to reduce redundancy" },
      { id: "t9", topic: "Security", question: "What does HTTPS provide over HTTP?", options: ["Faster speed", "Encryption and security", "Better compression", "More bandwidth"], answer: "Encryption and security" },
      { id: "t10", topic: "Web Development", question: "Which of the following is a CSS framework?", options: ["Bootstrap", "jQuery", "Node.js", "Express"], answer: "Bootstrap" },
      { id: "t11", topic: "Web Development", question: "What is the virtual DOM in React?", options: ["A server-side rendering technique", "A lightweight copy of the real DOM", "A database", "A CSS framework"], answer: "A lightweight copy of the real DOM" },
      { id: "t12", topic: "Security", question: "What is XSS attack?", options: ["Cross-Site Scripting that injects malicious scripts", "A database attack", "A network attack", "A phishing attack"], answer: "Cross-Site Scripting that injects malicious scripts" },
      { id: "t13", topic: "Networks", question: "What is an IP address?", options: ["A unique identifier for a device on a network", "A website URL", "A type of protocol", "A network cable"], answer: "A unique identifier for a device on a network" },
      { id: "t14", topic: "Web Development", question: "What is Node.js?", options: ["A frontend framework", "A JavaScript runtime for server-side development", "A database", "A CSS preprocessor"], answer: "A JavaScript runtime for server-side development" },
      { id: "t15", topic: "Database", question: "What is a foreign key?", options: ["A key from another country", "A field that references the primary key of another table", "An encrypted key", "An index"], answer: "A field that references the primary key of another table" },
      { id: "t16", topic: "Security", question: "What is two-factor authentication?", options: ["Using two passwords", "Verifying identity using two different methods", "Encrypting data twice", "Having two accounts"], answer: "Verifying identity using two different methods" },
      { id: "t17", topic: "Web Development", question: "What is an API?", options: ["A type of database", "Application Programming Interface for communication between systems", "A frontend library", "A server"], answer: "Application Programming Interface for communication between systems" },
      { id: "t18", topic: "Networks", question: "What is bandwidth?", options: ["The speed of a computer", "The maximum data transfer rate of a network", "The size of a file", "The number of users"], answer: "The maximum data transfer rate of a network" },
      { id: "t19", topic: "Security", question: "What is a VPN?", options: ["Virtual Private Network that encrypts internet traffic", "A type of firewall", "A web server", "A database"], answer: "Virtual Private Network that encrypts internet traffic" },
      { id: "t20", topic: "Web Development", question: "What is JWT?", options: ["Java Web Token", "JSON Web Token used for authentication", "JavaScript Web Tool", "None"], answer: "JSON Web Token used for authentication" },
      { id: "t21", topic: "Database", question: "What is MongoDB?", options: ["A relational database", "A NoSQL document database", "A SQL database", "A cloud service"], answer: "A NoSQL document database" },
      { id: "t22", topic: "Security", question: "What is phishing?", options: ["A fishing game", "A social engineering attack to steal credentials", "A network protocol", "An encryption method"], answer: "A social engineering attack to steal credentials" },
      { id: "t23", topic: "Web Development", question: "What does async/await do in JavaScript?", options: ["Makes code run faster", "Handles asynchronous operations more cleanly", "Encrypts data", "Creates animations"], answer: "Handles asynchronous operations more cleanly" },
      { id: "t24", topic: "Networks", question: "What is a proxy server?", options: ["A backup server", "An intermediary server between client and internet", "A database server", "A web server"], answer: "An intermediary server between client and internet" },
      { id: "t25", topic: "Security", question: "What is encryption?", options: ["Deleting data", "Converting data into a secure format that requires a key to read", "Compressing data", "Backing up data"], answer: "Converting data into a secure format that requires a key to read" },
      { id: "t26", topic: "Web Development", question: "What is the purpose of package.json in Node.js?", options: ["To store user data", "To manage project dependencies and scripts", "To configure the database", "To style the application"], answer: "To manage project dependencies and scripts" },
      { id: "t27", topic: "Database", question: "What is caching?", options: ["Deleting old data", "Storing frequently accessed data for faster retrieval", "Encrypting data", "Compressing data"], answer: "Storing frequently accessed data for faster retrieval" },
      { id: "t28", topic: "Security", question: "What is CORS?", options: ["Cross-Origin Resource Sharing that controls cross-domain requests", "A security protocol", "A type of encryption", "A database security feature"], answer: "Cross-Origin Resource Sharing that controls cross-domain requests" },
      { id: "t29", topic: "Web Development", question: "What is Tailwind CSS?", options: ["A JavaScript framework", "A utility-first CSS framework", "A backend framework", "A database ORM"], answer: "A utility-first CSS framework" },
      { id: "t30", topic: "Networks", question: "What is load balancing?", options: ["Reducing server load by turning off servers", "Distributing network traffic across multiple servers", "Increasing bandwidth", "Compressing network packets"], answer: "Distributing network traffic across multiple servers" },
      { id: "t31", topic: "Web Development", question: "Which HTML tag is used to create a hyperlink?", options: ["<link>", "<a>", "<href>", "<url>"], answer: "<a>" },
      { id: "t32", topic: "Networks", question: "Which protocol is used to send emails?", options: ["HTTP", "SMTP", "FTP", "SNMP"], answer: "SMTP" },
      { id: "t33", topic: "Database", question: "Which command is used to remove all records from a table without deleting the structure?", options: ["DELETE", "DROP", "TRUNCATE", "REMOVE"], answer: "TRUNCATE" },
      { id: "t34", topic: "Security", question: "What is a brute force attack?", options: ["Guessing passwords repeatedly", "Injecting SQL queries", "Phishing emails", "Encrypting files"], answer: "Guessing passwords repeatedly" },
      { id: "t35", topic: "Web Development", question: "What does CSS stand for?", options: ["Computer Style Sheets", "Cascading Style Sheets", "Creative Style System", "Colorful Style Sheets"], answer: "Cascading Style Sheets" },
      { id: "t36", topic: "Networks", question: "What is the full form of LAN?", options: ["Local Area Network", "Large Area Network", "Logical Access Network", "Light Area Network"], answer: "Local Area Network" },
      { id: "t37", topic: "Database", question: "What is a composite key?", options: ["A key with duplicate values", "A key made of multiple columns", "A foreign key", "An index"], answer: "A key made of multiple columns" },
      { id: "t38", topic: "Security", question: "What is hashing?", options: ["Encrypting data with a key", "Converting data into a fixed-length value", "Compressing files", "Backing up data"], answer: "Converting data into a fixed-length value" },
      { id: "t39", topic: "Web Development", question: "Which JavaScript keyword is used to declare a constant?", options: ["var", "let", "const", "static"], answer: "const" },
      { id: "t40", topic: "Networks", question: "What is the function of a router?", options: ["Store data", "Connect multiple networks and route traffic", "Encrypt data", "Host websites"], answer: "Connect multiple networks and route traffic" },
      { id: "t41", topic: "Database", question: "What does SQL stand for?", options: ["Structured Query Language", "Simple Query Language", "Sequential Query Language", "Standard Query Logic"], answer: "Structured Query Language" },
      { id: "t42", topic: "Security", question: "What is a digital signature?", options: ["A handwritten signature", "A code to verify authenticity and integrity of data", "A password", "An IP address"], answer: "A code to verify authenticity and integrity of data" },
      { id: "t43", topic: "Web Development", question: "Which HTTP status code indicates 'Not Found'?", options: ["200", "301", "404", "500"], answer: "404" },
      { id: "t44", topic: "Networks", question: "Which topology connects all devices to a central hub?", options: ["Bus", "Ring", "Star", "Mesh"], answer: "Star" },
      { id: "t45", topic: "Database", question: "What is denormalization?", options: ["Removing redundancy", "Adding redundancy for performance", "Encrypting data", "Backing up data"], answer: "Adding redundancy for performance" },
      { id: "t46", topic: "Security", question: "What is malware?", options: ["A security protocol", "Malicious software designed to harm systems", "A firewall", "An antivirus"], answer: "Malicious software designed to harm systems" },
      { id: "t47", topic: "Web Development", question: "Which framework is used for backend development in Node.js?", options: ["React", "Angular", "Express", "Vue"], answer: "Express" },
      { id: "t48", topic: "Networks", question: "What is latency in networking?", options: ["Data size", "Delay in data transmission", "Bandwidth", "Packet loss"], answer: "Delay in data transmission" },
      { id: "t49", topic: "Database", question: "Which type of database stores data in key-value pairs?", options: ["Relational", "Document", "Key-Value", "Graph"], answer: "Key-Value" },
      { id: "t50", topic: "Security", question: "What is an SSL certificate?", options: ["A database license", "A certificate that enables encrypted connections", "A firewall tool", "A network protocol"], answer: "A certificate that enables encrypted connections" }
    ],
  },

  aptitude: [
    { id: "a1", topic: "Quantitative", question: "If a train travels 60 km in 1 hour, how far will it travel in 2.5 hours?", options: ["120 km", "130 km", "150 km", "160 km"], answer: "150 km" },
    { id: "a2", topic: "Logical Reasoning", question: "Find the next number: 2, 4, 8, 16, ?", options: ["24", "32", "28", "30"], answer: "32" },
    { id: "a3", topic: "Verbal", question: "Choose the synonym of 'Eloquent':", options: ["Silent", "Fluent", "Rude", "Confused"], answer: "Fluent" },
    { id: "a4", topic: "Quantitative", question: "What is 15% of 200?", options: ["25", "30", "35", "40"], answer: "30" },
    { id: "a5", topic: "Logical Reasoning", question: "If all cats are animals and all animals have hearts, then:", options: ["Some cats have no hearts", "All cats have hearts", "No cats have hearts", "Cannot be determined"], answer: "All cats have hearts" },
    { id: "a6", topic: "Data Interpretation", question: "A shop sells 100 items at ₹50 each and 50 items at ₹100 each. What is total revenue?", options: ["₹8,000", "₹10,000", "₹12,000", "₹15,000"], answer: "₹10,000" },
    { id: "a7", topic: "Quantitative", question: "If X + Y = 10 and X - Y = 4, what is X?", options: ["5", "6", "7", "8"], answer: "7" },
    { id: "a8", topic: "Logical Reasoning", question: "Odd one out: Apple, Mango, Carrot, Banana", options: ["Apple", "Mango", "Carrot", "Banana"], answer: "Carrot" },
    { id: "a9", topic: "Verbal", question: "Choose the antonym of 'Ancient':", options: ["Old", "Modern", "Historic", "Aged"], answer: "Modern" },
    { id: "a10", topic: "Quantitative", question: "A car depreciates 10% per year. If it costs ₹1,00,000 now, what is its value after 1 year?", options: ["₹85,000", "₹90,000", "₹95,000", "₹80,000"], answer: "₹90,000" },
    { id: "a11", topic: "Quantitative", question: "A worker completes a job in 8 days. How much work does he complete in 3 days?", options: ["1/4", "3/8", "1/2", "3/4"], answer: "3/8" },
    { id: "a12", topic: "Logical Reasoning", question: "Find the missing: 1, 4, 9, 16, ?", options: ["20", "25", "22", "18"], answer: "25" },
    { id: "a13", topic: "Verbal", question: "Choose the synonym of 'Benevolent':", options: ["Cruel", "Kind", "Angry", "Lazy"], answer: "Kind" },
    { id: "a14", topic: "Quantitative", question: "Simple interest on ₹5000 at 8% per year for 3 years?", options: ["₹1000", "₹1200", "₹1500", "₹1800"], answer: "₹1200" },
    { id: "a15", topic: "Logical Reasoning", question: "If APPLE is coded as 12345, what is LEAP?", options: ["3412", "4312", "3421", "4321"], answer: "3412" },
    { id: "a16", topic: "Data Interpretation", question: "If 40% of a number is 80, what is the number?", options: ["150", "180", "200", "220"], answer: "200" },
    { id: "a17", topic: "Quantitative", question: "A train 100m long passes a pole in 10 seconds. What is its speed?", options: ["5 m/s", "8 m/s", "10 m/s", "12 m/s"], answer: "10 m/s" },
    { id: "a18", topic: "Logical Reasoning", question: "A is taller than B. B is taller than C. Who is shortest?", options: ["A", "B", "C", "Cannot determine"], answer: "C" },
    { id: "a19", topic: "Verbal", question: "Choose the antonym of 'Transparent':", options: ["Clear", "Opaque", "Bright", "Shiny"], answer: "Opaque" },
    { id: "a20", topic: "Quantitative", question: "Find the average of 10, 20, 30, 40, 50:", options: ["25", "30", "35", "40"], answer: "30" },
    { id: "a21", topic: "Quantitative", question: "If the price increases by 20% and then decreases by 20%, net change is?", options: ["0%", "-4%", "+4%", "-2%"], answer: "-4%" },
    { id: "a22", topic: "Logical Reasoning", question: "Find the odd one: 2, 3, 5, 7, 9, 11", options: ["2", "9", "5", "11"], answer: "9" },
    { id: "a23", topic: "Verbal", question: "Choose the correct spelling:", options: ["Accomodate", "Accommodate", "Acommodate", "Acomodate"], answer: "Accommodate" },
    { id: "a24", topic: "Data Interpretation", question: "Sales in Jan=100, Feb=150, Mar=200. Average monthly sales?", options: ["133", "150", "160", "175"], answer: "150" },
    { id: "a25", topic: "Quantitative", question: "Ratio of 3:4 — if smaller is 75, what is larger?", options: ["90", "100", "110", "120"], answer: "100" },
    { id: "a26", topic: "Logical Reasoning", question: "Pointing to a man, a woman says 'His mother is my mother's only daughter'. How is she related?", options: ["Mother", "Sister", "Aunt", "Grandmother"], answer: "Mother" },
    { id: "a27", topic: "Verbal", question: "Choose the synonym of 'Ambiguous':", options: ["Clear", "Vague", "Precise", "Definite"], answer: "Vague" },
    { id: "a28", topic: "Quantitative", question: "Compound interest on ₹1000 at 10% for 2 years?", options: ["₹200", "₹210", "₹220", "₹250"], answer: "₹210" },
    { id: "a29", topic: "Logical Reasoning", question: "If TODAY is WRGCA, then TOMORROW is?", options: ["WRGQTTQZ", "WRPRQTTQ", "WRPQTTQZ", "None"], answer: "WRPQTTQZ" },
    { id: "a30", topic: "Data Interpretation", question: "A pie chart shows 25% for Education. If total is 360°, what is Education's angle?", options: ["45°", "60°", "90°", "120°"], answer: "90°" },
    { id: "a31", topic: "Quantitative", question: "What is 25% of 480?", options: ["100", "110", "120", "130"], answer: "120" },
    { id: "a32", topic: "Logical Reasoning", question: "Find the next number: 3, 9, 27, ?", options: ["54", "72", "81", "90"], answer: "81" },
    { id: "a33", topic: "Verbal", question: "Choose the antonym of 'Generous':", options: ["Kind", "Selfish", "Helpful", "Polite"], answer: "Selfish" },
    { id: "a34", topic: "Quantitative", question: "If 5 pens cost ₹50, what is the cost of 12 pens?", options: ["₹100", "₹110", "₹120", "₹130"], answer: "₹120" },
    { id: "a35", topic: "Logical Reasoning", question: "Find the odd one out: 4, 9, 16, 25, 30", options: ["4", "9", "16", "30"], answer: "30" },
    { id: "a36", topic: "Data Interpretation", question: "If total students are 200 and 60% are boys, how many girls are there?", options: ["60", "70", "80", "90"], answer: "80" },
    { id: "a37", topic: "Quantitative", question: "Solve: 12 × 8 ÷ 4 =", options: ["12", "16", "20", "24"], answer: "24" },
    { id: "a38", topic: "Logical Reasoning", question: "If A=1, B=2, C=3, what is value of CAB?", options: ["312", "213", "231", "321"], answer: "312" },
    { id: "a39", topic: "Verbal", question: "Choose the synonym of 'Rapid':", options: ["Slow", "Fast", "Lazy", "Weak"], answer: "Fast" },
    { id: "a40", topic: "Quantitative", question: "What is the square root of 144?", options: ["10", "11", "12", "13"], answer: "12" },
    { id: "a41", topic: "Quantitative", question: "If 8 workers can complete a task in 6 days, how many days will 4 workers take?", options: ["10", "12", "14", "16"], answer: "12" },
    { id: "a42", topic: "Logical Reasoning", question: "Find the next term: 5, 10, 20, 40, ?", options: ["60", "70", "80", "90"], answer: "80" },
    { id: "a43", topic: "Verbal", question: "Choose the correct meaning of 'Meticulous':", options: ["Careless", "Detailed and careful", "Lazy", "Fast"], answer: "Detailed and careful" },
    { id: "a44", topic: "Quantitative", question: "A number increased by 20% becomes 120. What is the original number?", options: ["80", "90", "100", "110"], answer: "100" },
    { id: "a45", topic: "Logical Reasoning", question: "If RED is coded as 7-5-4, what is code for BLUE?", options: ["2-3-4-5", "2-12-21-5", "3-12-21-5", "2-11-20-4"], answer: "2-12-21-5" },
    { id: "a46", topic: "Data Interpretation", question: "If total revenue is ₹5000 and profit is 20%, what is profit amount?", options: ["₹800", "₹900", "₹1000", "₹1200"], answer: "₹1000" },
    { id: "a47", topic: "Quantitative", question: "Find the LCM of 6 and 8:", options: ["12", "18", "24", "30"], answer: "24" },
    { id: "a48", topic: "Logical Reasoning", question: "Which word does NOT belong: Dog, Cat, Cow, Car", options: ["Dog", "Cat", "Cow", "Car"], answer: "Car" },
    { id: "a49", topic: "Verbal", question: "Choose the antonym of 'Expand':", options: ["Increase", "Grow", "Shrink", "Extend"], answer: "Shrink" },
    { id: "a50", topic: "Quantitative", question: "If a number is divided by 5, the result is 12. What is the number?", options: ["50", "55", "60", "65"], answer: "60" }
  ],

  softskills: [
    { id: "s1", topic: "Communication", question: "Which of the following is the most effective way to communicate in a team?", options: ["Send long emails", "Use clear and concise language", "Avoid asking questions", "Only communicate when necessary"], answer: "Use clear and concise language" },
    { id: "s2", topic: "Leadership", question: "A good leader should:", options: ["Make all decisions alone", "Delegate tasks and empower team members", "Avoid feedback from team", "Focus only on results"], answer: "Delegate tasks and empower team members" },
    { id: "s3", topic: "Team Work", question: "When there is a conflict in a team, the best approach is to:", options: ["Ignore it", "Take sides", "Address it openly and find a solution", "Report to management immediately"], answer: "Address it openly and find a solution" },
    { id: "s4", topic: "Problem Solving", question: "What is the first step in problem solving?", options: ["Implement the solution", "Identify and define the problem", "Brainstorm solutions", "Evaluate results"], answer: "Identify and define the problem" },
    { id: "s5", topic: "Communication", question: "Active listening means:", options: ["Waiting for your turn to speak", "Fully concentrating and understanding the speaker", "Nodding without understanding", "Taking notes only"], answer: "Fully concentrating and understanding the speaker" },
    { id: "s6", topic: "Leadership", question: "Which leadership style involves team members in decision making?", options: ["Autocratic", "Laissez-faire", "Democratic", "Transactional"], answer: "Democratic" },
    { id: "s7", topic: "Team Work", question: "What makes a team highly effective?", options: ["Individual competition", "Clear roles, trust and communication", "Working in isolation", "Avoiding meetings"], answer: "Clear roles, trust and communication" },
    { id: "s8", topic: "Problem Solving", question: "Critical thinking involves:", options: ["Accepting all information as true", "Analyzing facts to form a judgment", "Following instructions blindly", "Avoiding complex situations"], answer: "Analyzing facts to form a judgment" },
    { id: "s9", topic: "Communication", question: "Non-verbal communication includes:", options: ["Emails", "Reports", "Body language and facial expressions", "Phone calls"], answer: "Body language and facial expressions" },
    { id: "s10", topic: "Leadership", question: "Emotional intelligence in leadership means:", options: ["Being emotional at work", "Understanding and managing your emotions and others", "Avoiding emotional situations", "Ignoring team feelings"], answer: "Understanding and managing your emotions and others" },
    { id: "s11", topic: "Communication", question: "What is the 7-38-55 rule in communication?", options: ["7% words, 38% tone, 55% body language", "7% body language, 38% words, 55% tone", "7% tone, 38% body language, 55% words", "None of these"], answer: "7% words, 38% tone, 55% body language" },
    { id: "s12", topic: "Team Work", question: "What is the Tuckman model of team development?", options: ["Plan, Do, Check, Act", "Forming, Storming, Norming, Performing", "Initiate, Plan, Execute, Close", "None"], answer: "Forming, Storming, Norming, Performing" },
    { id: "s13", topic: "Leadership", question: "What is servant leadership?", options: ["Leader serves only themselves", "Leader prioritizes the needs of the team", "Leader avoids responsibility", "Leader micromanages"], answer: "Leader prioritizes the needs of the team" },
    { id: "s14", topic: "Problem Solving", question: "What is root cause analysis?", options: ["Finding the symptom of a problem", "Identifying the fundamental cause of a problem", "Ignoring the problem", "Treating surface-level issues"], answer: "Identifying the fundamental cause of a problem" },
    { id: "s15", topic: "Communication", question: "What is assertive communication?", options: ["Aggressive communication", "Expressing yourself clearly while respecting others", "Passive communication", "Avoiding communication"], answer: "Expressing yourself clearly while respecting others" },
    { id: "s16", topic: "Leadership", question: "What is SMART goal setting?", options: ["Simple, Measurable, Achievable, Relevant, Time-bound", "Specific, Measurable, Achievable, Relevant, Time-bound", "Strategic, Meaningful, Actionable, Realistic, Timely", "None"], answer: "Specific, Measurable, Achievable, Relevant, Time-bound" },
    { id: "s17", topic: "Team Work", question: "What is psychological safety in a team?", options: ["Physical safety at workplace", "Feeling safe to speak up without fear of punishment", "Job security", "Financial safety"], answer: "Feeling safe to speak up without fear of punishment" },
    { id: "s18", topic: "Problem Solving", question: "What is design thinking?", options: ["Designing software", "A human-centered approach to problem solving", "Technical problem solving", "None"], answer: "A human-centered approach to problem solving" },
    { id: "s19", topic: "Communication", question: "What is feedback sandwich?", options: ["Positive-Negative-Positive feedback", "Only positive feedback", "Only negative feedback", "No feedback"], answer: "Positive-Negative-Positive feedback" },
    { id: "s20", topic: "Leadership", question: "What is transformational leadership?", options: ["Maintaining status quo", "Inspiring and motivating team to exceed expectations", "Following strict rules", "Avoiding change"], answer: "Inspiring and motivating team to exceed expectations" },
    { id: "s21", topic: "Team Work", question: "How should you handle a team member who is not contributing?", options: ["Ignore them", "Have a private, constructive conversation", "Report immediately to HR", "Do their work yourself"], answer: "Have a private, constructive conversation" },
    { id: "s22", topic: "Problem Solving", question: "What is brainstorming?", options: ["Individual thinking", "Generating multiple ideas without judgment as a group", "Criticizing ideas", "Following existing solutions"], answer: "Generating multiple ideas without judgment as a group" },
    { id: "s23", topic: "Communication", question: "What is the most important element of a professional email?", options: ["Fancy formatting", "Clear subject line and concise content", "Long detailed explanation", "Multiple attachments"], answer: "Clear subject line and concise content" },
    { id: "s24", topic: "Leadership", question: "What does accountability mean in leadership?", options: ["Blaming others for failures", "Taking responsibility for actions and outcomes", "Avoiding difficult decisions", "Delegating all tasks"], answer: "Taking responsibility for actions and outcomes" },
    { id: "s25", topic: "Team Work", question: "What is cross-functional collaboration?", options: ["Working only within your department", "Working with people from different departments", "Remote working", "Part-time collaboration"], answer: "Working with people from different departments" },
    { id: "s26", topic: "Problem Solving", question: "What is the 5 Whys technique?", options: ["Asking why 5 times to find root cause", "A 5-step problem solving process", "Five people solving one problem", "None"], answer: "Asking why 5 times to find root cause" },
    { id: "s27", topic: "Communication", question: "What is empathy in communication?", options: ["Feeling sorry for someone", "Understanding and sharing the feelings of another", "Giving advice", "Being sympathetic"], answer: "Understanding and sharing the feelings of another" },
    { id: "s28", topic: "Leadership", question: "What is the difference between management and leadership?", options: ["No difference", "Management focuses on tasks, leadership focuses on people and vision", "Leadership is higher than management", "Management is more important"], answer: "Management focuses on tasks, leadership focuses on people and vision" },
    { id: "s29", topic: "Team Work", question: "What is agile methodology?", options: ["A programming language", "An iterative approach to project management and software development", "A leadership style", "A communication framework"], answer: "An iterative approach to project management and software development" },
    { id: "s30", topic: "Problem Solving", question: "What is the Pareto principle in problem solving?", options: ["80% of problems come from 20% of causes", "All problems are equally important", "Focus on all problems equally", "None"], answer: "80% of problems come from 20% of causes" },
    { id: "s31", topic: "Communication", question: "What is clarity in communication?", options: ["Using complex words", "Delivering message in a simple and understandable way", "Speaking loudly", "Avoiding details"], answer: "Delivering message in a simple and understandable way" },
    { id: "s32", topic: "Leadership", question: "What is delegation?", options: ["Doing all tasks yourself", "Assigning tasks to others with responsibility", "Avoiding tasks", "Ignoring team members"], answer: "Assigning tasks to others with responsibility" },
    { id: "s33", topic: "Team Work", question: "What is collaboration?", options: ["Working alone", "Working together to achieve a common goal", "Competing with teammates", "Avoiding communication"], answer: "Working together to achieve a common goal" },
    { id: "s34", topic: "Problem Solving", question: "What is decision making?", options: ["Avoiding choices", "Selecting the best option among alternatives", "Following others blindly", "Ignoring problems"], answer: "Selecting the best option among alternatives" },
    { id: "s35", topic: "Communication", question: "What is tone in communication?", options: ["Words used", "Pitch and attitude in voice", "Grammar rules", "Body posture"], answer: "Pitch and attitude in voice" },
    { id: "s36", topic: "Leadership", question: "What is vision in leadership?", options: ["Short-term task list", "A clear picture of future goals", "Daily routine", "Team conflict"], answer: "A clear picture of future goals" },
    { id: "s37", topic: "Team Work", question: "What is mutual respect in a team?", options: ["Ignoring others", "Valuing each team member’s opinions", "Competing constantly", "Avoiding feedback"], answer: "Valuing each team member’s opinions" },
    { id: "s38", topic: "Problem Solving", question: "What is analytical thinking?", options: ["Guessing answers", "Breaking down problems into parts to understand them", "Ignoring details", "Following instincts only"], answer: "Breaking down problems into parts to understand them" },
    { id: "s39", topic: "Communication", question: "What is feedback in communication?", options: ["Ignoring responses", "Response given to improve performance", "Only criticism", "Only praise"], answer: "Response given to improve performance" },
    { id: "s40", topic: "Leadership", question: "What is motivation in leadership?", options: ["Forcing employees to work", "Encouraging team members to achieve goals", "Ignoring team needs", "Setting strict rules"], answer: "Encouraging team members to achieve goals" },
    { id: "s41", topic: "Team Work", question: "What is accountability in teamwork?", options: ["Blaming others", "Taking responsibility for your tasks", "Avoiding work", "Delegating everything"], answer: "Taking responsibility for your tasks" },
    { id: "s42", topic: "Problem Solving", question: "What is creativity in problem solving?", options: ["Following old methods", "Thinking of new and innovative solutions", "Avoiding risks", "Ignoring ideas"], answer: "Thinking of new and innovative solutions" },
    { id: "s43", topic: "Communication", question: "What is paraphrasing?", options: ["Repeating exactly", "Restating information in your own words", "Ignoring message", "Changing topic"], answer: "Restating information in your own words" },
    { id: "s44", topic: "Leadership", question: "What is integrity in leadership?", options: ["Being dishonest", "Acting with honesty and strong moral principles", "Avoiding responsibility", "Ignoring rules"], answer: "Acting with honesty and strong moral principles" },
    { id: "s45", topic: "Team Work", question: "What is team cohesion?", options: ["Team conflict", "Strong bonding and unity among members", "Working alone", "Avoiding meetings"], answer: "Strong bonding and unity among members" },
    { id: "s46", topic: "Problem Solving", question: "What is risk analysis?", options: ["Ignoring risks", "Identifying and evaluating potential risks", "Creating problems", "Avoiding decisions"], answer: "Identifying and evaluating potential risks" },
    { id: "s47", topic: "Communication", question: "What is listening barrier?", options: ["Clear understanding", "Anything that prevents effective listening", "Speaking clearly", "Writing emails"], answer: "Anything that prevents effective listening" },
    { id: "s48", topic: "Leadership", question: "What is adaptability in leadership?", options: ["Sticking to one method", "Adjusting to new situations and challenges", "Avoiding change", "Ignoring feedback"], answer: "Adjusting to new situations and challenges" },
    { id: "s49", topic: "Team Work", question: "What is conflict resolution?", options: ["Avoiding conflict", "Resolving disagreements constructively", "Ignoring issues", "Blaming others"], answer: "Resolving disagreements constructively" },
    { id: "s50", topic: "Problem Solving", question: "What is evaluation in problem solving?", options: ["Skipping results", "Assessing effectiveness of a solution", "Ignoring outcomes", "Repeating same process"], answer: "Assessing effectiveness of a solution" }
  ],
};

export const roadmaps = {
  Python: {
    steps: [
      "Complete Python Basics on W3Schools",
      "Practice on HackerRank Python track",
      "Build 2 Python projects",
    ],
    videos: [
      { title: "Python Full Course for Beginners", channel: "Programming with Mosh", url: "https://www.youtube.com/results?search_query=Python+full+course+for+beginners+Programming+with+Mosh" },
      { title: "Python Tutorial - freeCodeCamp", channel: "freeCodeCamp", url: "https://www.youtube.com/results?search_query=Python+full+course+freecodecamp+beginners" },
      { title: "Python for Data Science", channel: "Corey Schafer", url: "https://www.youtube.com/results?search_query=Python+data+science+Corey+Schafer" },
    ],
  },
  "Machine Learning": {
    steps: [
      "Study Andrew Ng's ML course on Coursera",
      "Practice Kaggle competitions",
      "Implement 3 ML algorithms from scratch",
    ],
    videos: [
      { title: "Machine Learning Full Course", channel: "Simplilearn", url: "https://www.youtube.com/results?search_query=machine+learning+full+course+simplilearn" },
      { title: "ML for Beginners - freeCodeCamp", channel: "freeCodeCamp", url: "https://www.youtube.com/results?search_query=machine+learning+for+beginners+freecodecamp" },
      { title: "StatQuest Machine Learning", channel: "StatQuest", url: "https://www.youtube.com/results?search_query=statquest+machine+learning+basics" },
    ],
  },
  "Data Analysis": {
    steps: [
      "Learn Pandas and NumPy",
      "Practice EDA on Kaggle datasets",
      "Build a data analysis portfolio project",
    ],
    videos: [
      { title: "Pandas Full Course", channel: "Corey Schafer", url: "https://www.youtube.com/results?search_query=pandas+tutorial+corey+schafer" },
      { title: "Data Analysis with Python", channel: "freeCodeCamp", url: "https://www.youtube.com/results?search_query=data+analysis+python+freecodecamp" },
      { title: "Exploratory Data Analysis Tutorial", channel: "Ken Jee", url: "https://www.youtube.com/results?search_query=exploratory+data+analysis+python+tutorial" },
    ],
  },
  "Deep Learning": {
    steps: [
      "Study Neural Networks basics",
      "Complete fast.ai course",
      "Build an image classification project",
    ],
    videos: [
      { title: "Deep Learning Full Course", channel: "Simplilearn", url: "https://www.youtube.com/results?search_query=deep+learning+full+course+beginners" },
      { title: "Neural Networks from Scratch", channel: "Sentdex", url: "https://www.youtube.com/results?search_query=neural+networks+from+scratch+python+sentdex" },
      { title: "Deep Learning with PyTorch", channel: "freeCodeCamp", url: "https://www.youtube.com/results?search_query=deep+learning+pytorch+freecodecamp" },
    ],
  },
  "Web Development": {
    steps: [
      "Complete HTML/CSS/JS basics",
      "Learn React.js from official docs",
      "Build a full stack project",
    ],
    videos: [
      { title: "React JS Full Course", channel: "Programming with Mosh", url: "https://www.youtube.com/results?search_query=react+js+full+course+programming+with+mosh" },
      { title: "Full Stack Web Development", channel: "freeCodeCamp", url: "https://www.youtube.com/results?search_query=full+stack+web+development+freecodecamp" },
      { title: "HTML CSS JavaScript Course", channel: "Dave Gray", url: "https://www.youtube.com/results?search_query=HTML+CSS+JavaScript+full+course+dave+gray" },
    ],
  },
  Database: {
    steps: [
      "Learn SQL on SQLZoo",
      "Practice MongoDB queries",
      "Design a database schema for a real project",
    ],
    videos: [
      { title: "SQL Full Course", channel: "Programming with Mosh", url: "https://www.youtube.com/results?search_query=SQL+full+course+programming+with+mosh" },
      { title: "MongoDB Full Course", channel: "Traversy Media", url: "https://www.youtube.com/results?search_query=mongodb+full+course+traversy+media" },
      { title: "Database Design Course", channel: "freeCodeCamp", url: "https://www.youtube.com/results?search_query=database+design+course+freecodecamp" },
    ],
  },
  DSA: {
    steps: [
      "Study arrays, linked lists, trees",
      "Practice 50 LeetCode problems",
      "Learn dynamic programming",
    ],
    videos: [
      { title: "Data Structures Full Course", channel: "freeCodeCamp", url: "https://www.youtube.com/results?search_query=data+structures+algorithms+full+course+freecodecamp" },
      { title: "Algorithms and Data Structures", channel: "Programming with Mosh", url: "https://www.youtube.com/results?search_query=algorithms+data+structures+programming+with+mosh" },
      { title: "Dynamic Programming for Beginners", channel: "NeetCode", url: "https://www.youtube.com/results?search_query=dynamic+programming+beginners+neetcode" },
    ],
  },
  OS: {
    steps: [
      "Read Operating Systems by Tanenbaum",
      "Study process scheduling algorithms",
      "Understand memory management",
    ],
    videos: [
      { title: "Operating Systems Full Course", channel: "Neso Academy", url: "https://www.youtube.com/results?search_query=operating+systems+full+course+neso+academy" },
      { title: "OS Concepts for Beginners", channel: "Gate Smashers", url: "https://www.youtube.com/results?search_query=operating+system+concepts+gate+smashers" },
      { title: "Process Scheduling Algorithms", channel: "Neso Academy", url: "https://www.youtube.com/results?search_query=process+scheduling+algorithms+os+tutorial" },
    ],
  },
  Networks: {
    steps: [
      "Study OSI and TCP/IP models",
      "Learn about HTTP, DNS, firewalls",
      "Set up a small home network",
    ],
    videos: [
      { title: "Computer Networking Full Course", channel: "freeCodeCamp", url: "https://www.youtube.com/results?search_query=computer+networking+full+course+freecodecamp" },
      { title: "OSI Model Explained", channel: "Practical Networking", url: "https://www.youtube.com/results?search_query=OSI+model+explained+practical+networking" },
      { title: "TCP/IP Model Tutorial", channel: "Neso Academy", url: "https://www.youtube.com/results?search_query=TCP+IP+model+tutorial+neso+academy" },
    ],
  },
  OOP: {
    steps: [
      "Study 4 pillars of OOP",
      "Implement design patterns",
      "Build an OOP-based project",
    ],
    videos: [
      { title: "Object Oriented Programming", channel: "Programming with Mosh", url: "https://www.youtube.com/results?search_query=object+oriented+programming+programming+with+mosh" },
      { title: "OOP Concepts Full Course", channel: "freeCodeCamp", url: "https://www.youtube.com/results?search_query=OOP+concepts+full+course+freecodecamp" },
      { title: "Design Patterns Tutorial", channel: "Derek Banas", url: "https://www.youtube.com/results?search_query=design+patterns+tutorial+derek+banas" },
    ],
  },
  Security: {
    steps: [
      "Learn OWASP Top 10",
      "Study cryptography basics",
      "Practice on TryHackMe",
    ],
    videos: [
      { title: "Ethical Hacking Full Course", channel: "freeCodeCamp", url: "https://www.youtube.com/results?search_query=ethical+hacking+full+course+freecodecamp" },
      { title: "Cybersecurity for Beginners", channel: "NetworkChuck", url: "https://www.youtube.com/results?search_query=cybersecurity+for+beginners+networkchuck" },
      { title: "OWASP Top 10 Explained", channel: "David Bombal", url: "https://www.youtube.com/results?search_query=OWASP+top+10+explained+david+bombal" },
    ],
  },
  Quantitative: {
    steps: [
      "Practice arithmetic and algebra daily",
      "Use IndiaBix for aptitude questions",
      "Solve 20 problems per day",
    ],
    videos: [
      { title: "Quantitative Aptitude Full Course", channel: "Unacademy", url: "https://www.youtube.com/results?search_query=quantitative+aptitude+full+course+placement" },
      { title: "Aptitude Tricks and Shortcuts", channel: "CareerRide", url: "https://www.youtube.com/results?search_query=aptitude+tricks+shortcuts+placement+preparation" },
      { title: "Maths for Competitive Exams", channel: "Adda247", url: "https://www.youtube.com/results?search_query=maths+shortcuts+competitive+exams+aptitude" },
    ],
  },
  "Logical Reasoning": {
    steps: [
      "Practice syllogisms and puzzles",
      "Use RS Aggarwal book",
      "Attempt mock tests weekly",
    ],
    videos: [
      { title: "Logical Reasoning Full Course", channel: "Unacademy", url: "https://www.youtube.com/results?search_query=logical+reasoning+full+course+placement" },
      { title: "Reasoning Tricks for Placements", channel: "Study Smart", url: "https://www.youtube.com/results?search_query=reasoning+tricks+shortcuts+campus+placement" },
      { title: "Blood Relations and Puzzles", channel: "CareerRide", url: "https://www.youtube.com/results?search_query=blood+relations+puzzles+logical+reasoning" },
    ],
  },
  Verbal: {
    steps: [
      "Read English newspapers daily",
      "Practice vocabulary on Merriam-Webster",
      "Attempt verbal reasoning tests",
    ],
    videos: [
      { title: "English Vocabulary Building", channel: "Learn English", url: "https://www.youtube.com/results?search_query=english+vocabulary+building+for+placement" },
      { title: "Verbal Ability for Placements", channel: "Unacademy", url: "https://www.youtube.com/results?search_query=verbal+ability+campus+placement+preparation" },
      { title: "English Grammar Full Course", channel: "EnglishLessons4U", url: "https://www.youtube.com/results?search_query=english+grammar+full+course+beginners" },
    ],
  },
  "Data Interpretation": {
    steps: [
      "Practice DI sets from previous CAT papers",
      "Learn to read graphs and tables quickly",
      "Solve 10 DI sets per week",
    ],
    videos: [
      { title: "Data Interpretation Tricks", channel: "Unacademy", url: "https://www.youtube.com/results?search_query=data+interpretation+tricks+shortcuts+placement" },
      { title: "DI for Campus Placements", channel: "CareerRide", url: "https://www.youtube.com/results?search_query=data+interpretation+campus+placement+preparation" },
      { title: "Bar Graph and Pie Chart DI", channel: "Study Smart", url: "https://www.youtube.com/results?search_query=bar+graph+pie+chart+data+interpretation+tutorial" },
    ],
  },
  Communication: {
    steps: [
      "Join a public speaking club",
      "Practice writing clear emails",
      "Record yourself speaking and review",
    ],
    videos: [
      { title: "Communication Skills Full Course", channel: "Simplilearn", url: "https://www.youtube.com/results?search_query=communication+skills+full+course+workplace" },
      { title: "Public Speaking Tips", channel: "Charisma on Command", url: "https://www.youtube.com/results?search_query=public+speaking+tips+charisma+on+command" },
      { title: "Business Communication Skills", channel: "Skillopedia", url: "https://www.youtube.com/results?search_query=business+communication+skills+professional" },
    ],
  },
  Leadership: {
    steps: [
      "Read 'Leaders Eat Last' by Simon Sinek",
      "Take on team lead roles in projects",
      "Practice giving constructive feedback",
    ],
    videos: [
      { title: "Leadership Skills Full Course", channel: "Simplilearn", url: "https://www.youtube.com/results?search_query=leadership+skills+full+course+management" },
      { title: "How Great Leaders Inspire Action", channel: "TED", url: "https://www.youtube.com/results?search_query=simon+sinek+how+great+leaders+inspire+action+TED" },
      { title: "Leadership vs Management", channel: "Brian Tracy", url: "https://www.youtube.com/results?search_query=leadership+vs+management+brian+tracy" },
    ],
  },
  "Team Work": {
    steps: [
      "Participate in group projects actively",
      "Practice conflict resolution techniques",
      "Study Agile and Scrum methodologies",
    ],
    videos: [
      { title: "Teamwork and Collaboration Skills", channel: "Simplilearn", url: "https://www.youtube.com/results?search_query=teamwork+collaboration+skills+workplace" },
      { title: "Scrum in 10 Minutes", channel: "Axosoft", url: "https://www.youtube.com/results?search_query=scrum+agile+tutorial+beginners" },
      { title: "Conflict Resolution at Work", channel: "Skillsyouneed", url: "https://www.youtube.com/results?search_query=conflict+resolution+workplace+skills" },
    ],
  },
  "Problem Solving": {
    steps: [
      "Practice design thinking",
      "Solve case studies daily",
      "Learn root cause analysis techniques",
    ],
    videos: [
      { title: "Problem Solving Skills", channel: "Simplilearn", url: "https://www.youtube.com/results?search_query=problem+solving+skills+critical+thinking" },
      { title: "Design Thinking Full Course", channel: "IDEO", url: "https://www.youtube.com/results?search_query=design+thinking+full+course+beginners" },
      { title: "Critical Thinking Skills", channel: "Improvement Pill", url: "https://www.youtube.com/results?search_query=critical+thinking+skills+improvement" },
    ],
  },
};